using BillingApp.Domain.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace BillingApp.Application.Services;

public class InvoicePdfExporter
{
    public void Export(string filePath, Invoice invoice, string customerName)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(32);
                page.Size(PageSizes.A4);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Column(column =>
                {
                    column.Item().Text("Billing App").FontSize(20).Bold();
                    column.Item().Text($"Invoice: {invoice.InvoiceNumber}");
                    column.Item().Text($"Customer: {customerName}");
                    column.Item().Text($"Issue Date: {invoice.IssueDate:yyyy-MM-dd}");
                    if (invoice.DateIn.HasValue)
                        column.Item().Text($"Date In: {invoice.DateIn:yyyy-MM-dd}");
                    if (invoice.DateOut.HasValue)
                        column.Item().Text($"Date Out: {invoice.DateOut:yyyy-MM-dd}");
                });

                page.Content().PaddingVertical(18).Column(column =>
                {
                    column.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(4);
                            columns.RelativeColumn(1);
                            columns.RelativeColumn(1.5f);
                            columns.RelativeColumn(1.2f);
                            columns.RelativeColumn(1.8f);
                        });

                        table.Header(header =>
                        {
                            header.Cell().Element(CellStyle).Text("Description").Bold();
                            header.Cell().Element(CellStyle).AlignRight().Text("Qty").Bold();
                            header.Cell().Element(CellStyle).AlignRight().Text("Unit Price").Bold();
                            header.Cell().Element(CellStyle).AlignRight().Text("Tax %").Bold();
                            header.Cell().Element(CellStyle).AlignRight().Text("Line Total").Bold();
                        });

                        foreach (var item in invoice.Items.OrderBy(i => i.LineNo))
                        {
                            table.Cell().Element(CellStyle).Text(BuildDescription(item));
                            table.Cell().Element(CellStyle).AlignRight().Text(item.Quantity.ToString("0.##"));
                            table.Cell().Element(CellStyle).AlignRight().Text(item.UnitPriceMinor.ToString());
                            table.Cell().Element(CellStyle).AlignRight().Text(item.TaxRate.ToString("0.##"));
                            table.Cell().Element(CellStyle).AlignRight().Text(item.LineTotalMinor.ToString());
                        }
                    });

                    column.Item().PaddingTop(16).AlignRight().Column(totals =>
                    {
                        totals.Item().Text($"Subtotal: {invoice.Totals.SubtotalMinor} {invoice.Currency}");
                        totals.Item().Text($"Tax: {invoice.Totals.TaxTotalMinor} {invoice.Currency}");
                        totals.Item().Text($"Grand Total: {invoice.Totals.GrandTotalMinor} {invoice.Currency}").Bold();
                    });
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by Billing App");
                });
            });
        }).GeneratePdf(filePath);
    }

    private static string BuildDescription(InvoiceItem item)
    {
        if (item.PricingRuleType != PricingRuleType.StorageDaily)
            return item.Description;

        return $"{item.Description}\nStorage: {item.StorageStartDate:yyyy-MM-dd} -> {item.StorageEndDate:yyyy-MM-dd} | Days: {item.StorageDays}";
    }

    private static IContainer CellStyle(IContainer container)
    {
        return container.BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingVertical(6).PaddingHorizontal(4);
    }
}
